// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_scanbt(lv_event_t * e);
extern lv_obj_t * ui_scanbt;
void ui_event_initbutton(lv_event_t * e);
extern lv_obj_t * ui_initbutton;
extern lv_obj_t * ui_logtextbox;
extern lv_obj_t * ui_initlb;
extern lv_obj_t * ui_titlelb;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_SliderSelectChannel;
extern lv_obj_t * ui_allchannelcheckbox;
extern lv_obj_t * ui_TransmissionSpeedDropdown;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_ScanBleResult;
extern lv_obj_t * ui_channel;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
