// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_SCANLB_H
#define _UI_COMP_SCANLB_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT scanlb
#define UI_COMP_SCANLB_SCANLB 0
#define _UI_COMP_SCANLB_NUM 1
lv_obj_t * ui_scanlb_create(lv_obj_t * comp_parent);
void ui_event_comp_scanlb_scanlb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
