// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_comp_scanlb_scanlb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_scanlb = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        scanble(e);
    }
}

// COMPONENT scanlb

lv_obj_t * ui_scanlb_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_scanlb;
    cui_scanlb = lv_label_create(comp_parent);
    lv_obj_set_width(cui_scanlb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_scanlb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_scanlb, -295);
    lv_obj_set_y(cui_scanlb, -69);
    lv_obj_set_align(cui_scanlb, LV_ALIGN_CENTER);
    lv_label_set_text(cui_scanlb, "SCAN BLE");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SCANLB_NUM);
    children[UI_COMP_SCANLB_SCANLB] = cui_scanlb;
    lv_obj_add_event_cb(cui_scanlb, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_scanlb, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_scanlb, ui_event_comp_scanlb_scanlb, LV_EVENT_ALL, children);
    ui_comp_scanlb_create_hook(cui_scanlb);
    return cui_scanlb;
}

