// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void scanble(lv_event_t * e)
{
	// Your code here
}

void initscanble(lv_event_t * e)
{
	// Your code here
}

void initjammer(lv_event_t * e)
{
	// Your code here
}
