// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_add_state(ui_Screen1, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scanbt = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_scanbt, 100);
    lv_obj_set_height(ui_scanbt, 26);
    lv_obj_set_x(ui_scanbt, -295);
    lv_obj_set_y(ui_scanbt, -68);
    lv_obj_set_align(ui_scanbt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scanbt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scanbt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_initbutton = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_initbutton, 109);
    lv_obj_set_height(ui_initbutton, 25);
    lv_obj_set_x(ui_initbutton, -293);
    lv_obj_set_y(ui_initbutton, 174);
    lv_obj_set_align(ui_initbutton, LV_ALIGN_CENTER);

    ui_logtextbox = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_logtextbox, 150);
    lv_obj_set_height(ui_logtextbox, 298);
    lv_obj_set_x(ui_logtextbox, 291);
    lv_obj_set_y(ui_logtextbox, 65);
    lv_obj_set_align(ui_logtextbox, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_logtextbox, "Placeholder...");

    ui_initlb = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_initlb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_initlb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_initlb, -291);
    lv_obj_set_y(ui_initlb, 148);
    lv_obj_set_align(ui_initlb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_initlb, "INIT");

    ui_titlelb = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_titlelb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titlelb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titlelb, -101);
    lv_obj_set_y(ui_titlelb, -153);
    lv_obj_set_align(ui_titlelb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titlelb, "NRF24 BLUETOOTH JAMMER");
    lv_obj_set_style_text_font(ui_titlelb, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titlelb, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_EDITED);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -117);
    lv_obj_set_y(ui_Label4, -65);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SELECT CHANNEL");

    ui_SliderSelectChannel = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_SliderSelectChannel, 2, 81);
    lv_slider_set_value(ui_SliderSelectChannel, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSelectChannel) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSelectChannel,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSelectChannel, 150);
    lv_obj_set_height(ui_SliderSelectChannel, 10);
    lv_obj_set_x(ui_SliderSelectChannel, -113);
    lv_obj_set_y(ui_SliderSelectChannel, -24);
    lv_obj_set_align(ui_SliderSelectChannel, LV_ALIGN_CENTER);

    ui_allchannelcheckbox = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_allchannelcheckbox, "ALL CHANNELS");
    lv_obj_set_width(ui_allchannelcheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_allchannelcheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_allchannelcheckbox, -110);
    lv_obj_set_y(ui_allchannelcheckbox, 8);
    lv_obj_set_align(ui_allchannelcheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_allchannelcheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_TransmissionSpeedDropdown = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_TransmissionSpeedDropdown, "RF24_250KBPS  \nRF24_1MBPS  \nRF24_2MBPS");
    lv_obj_set_width(ui_TransmissionSpeedDropdown, 150);
    lv_obj_set_height(ui_TransmissionSpeedDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TransmissionSpeedDropdown, 100);
    lv_obj_set_y(ui_TransmissionSpeedDropdown, -16);
    lv_obj_set_align(ui_TransmissionSpeedDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TransmissionSpeedDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 97);
    lv_obj_set_y(ui_Label5, -65);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "TRANSMISSION SPEED");

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 289);
    lv_obj_set_y(ui_Label6, -98);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "LOG");

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 249);
    lv_obj_set_height(ui_Chart1, 100);
    lv_obj_set_x(ui_Chart1, -2);
    lv_obj_set_y(ui_Chart1, 134);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    ui_ScanBleResult = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_ScanBleResult, 150);
    lv_obj_set_height(ui_ScanBleResult, 157);
    lv_obj_set_x(ui_ScanBleResult, -290);
    lv_obj_set_y(ui_ScanBleResult, 37);
    lv_obj_set_align(ui_ScanBleResult, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ScanBleResult, "Placeholder...");

    ui_channel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_channel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_channel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_channel, -23);
    lv_obj_set_y(ui_channel, -25);
    lv_obj_set_align(ui_channel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_channel, "");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -295);
    lv_obj_set_y(ui_Label2, -68);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SCAN BLE");

    lv_obj_add_event_cb(ui_scanbt, ui_event_scanbt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_initbutton, ui_event_initbutton, LV_EVENT_ALL, NULL);

}
